package pl.edu.mimuw.cloudatlas.interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public abstract class BasicExpr implements java.io.Serializable {
  public abstract <R,A> R accept(BasicExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(BasicExprAddC p, A arg);
    public R visit(BasicExprSubC p, A arg);
    public R visit(BasicExprMulC p, A arg);
    public R visit(BasicExprDivC p, A arg);
    public R visit(BasicExprModC p, A arg);
    public R visit(BasicExprNegC p, A arg);
    public R visit(EBoolC p, A arg);
    public R visit(EIdentC p, A arg);
    public R visit(EFunC p, A arg);
    public R visit(EStrC p, A arg);
    public R visit(EIntC p, A arg);
    public R visit(EDblC p, A arg);
    public R visit(ECondExprC p, A arg);
    public R visit(EStmtC p, A arg);

  }

}
