package pl.edu.mimuw.cloudatlas.interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public abstract class BoolExpr implements java.io.Serializable {
  public abstract <R,A> R accept(BoolExpr.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(BoolExprCmpC p, A arg);
    public R visit(BoolExprRegExpC p, A arg);
    public R visit(BoolExprBasicExprC p, A arg);

  }

}
