package pl.edu.mimuw.cloudatlas.interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public class EStmtC extends BasicExpr {
  public final Statement statement_;

  public EStmtC(Statement p1) { statement_ = p1; }

  public <R,A> R accept(BasicExpr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof EStmtC) {
      EStmtC x = (EStmtC)o;
      return this.statement_.equals(x.statement_);
    }
    return false;
  }

  public int hashCode() {
    return this.statement_.hashCode();
  }


}
