package pl.edu.mimuw.cloudatlas.interpreter.query.Absyn; // Java Package generated by the BNF Converter.

public abstract class RelOp implements java.io.Serializable {
  public abstract <R,A> R accept(RelOp.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(RelOpGtC p, A arg);
    public R visit(RelOpEqC p, A arg);
    public R visit(RelOpNeC p, A arg);
    public R visit(RelOpLtC p, A arg);
    public R visit(RelOpLeC p, A arg);
    public R visit(RelOpGeC p, A arg);

  }

}
